fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  format_listener:
      rules:
        - { path: '^/ajax', priorities: ['json'], fallback_format: json, prefer_extension: false }
        - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
  param_fetcher_listener: true
  access_denied_listener:
    json: true
  view:
    view_response_listener: 'force'
    formats:
      json: true